#spring:
#  datasource:
#    url: jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}
#    username: ${PGUSER}
#    password: ${PGPASSWORD}
#  jpa:
#    open-in-view: false
#    hibernate:
#      ddl-auto: create # validate | update | create | create-drop
#
spring:
  datasource:
    url: jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}
    username: ${PGUSER}
    password: ${PGPASSWORD}
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      open-in-view: false
      ddl-auto: update   # validate | update | create | create-drop
hibernate:
   dialect: org.hibernate.dialect.PostgreSQLDialect
